server:
  port: 9214

spring:
    application:
        name: profile-service
    r2dbc:
        url: r2dbc:pool:mysql://localhost:3307/profiledb
        username: root
        password:
    liquibase:
        url: jdbc:mysql://localhost:3307/profiledb
        enabled: true
        user: root
        password:
        change-log: classpath:db/changelog/changelog-master.xml
    kafka:
        producer:
            retries: 3
            batch-size: 16384
            buffer-memory: 33554432

kafka:
    bootstrap:
        servers: localhost:9092
payment:
    kafka:
        consumer-group-id: profileService-groupId
