server:
  port: 9214

spring:
    application:
        name: profile-service
    r2dbc:
        url: r2dbc:pool:mysql://localhost:3307/profiledb
        username: root
        password:
    liquibase:
        url: jdbc:mysql://localhost:3307/profiledb
        enabled: true
        user: root
        password:
        change-log: classpath:db/changelog/changelog-master.xml
